package com.github.okanikani223.vicar.books.others.controllers.dtos;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;
import java.util.Objects;

public record Book(
        @Schema(description = "Book ID, automatically generated by the system.", accessMode = Schema.AccessMode.READ_ONLY)
        String id,
        @Schema(description = "Book title. Required for registration.", example = "book title")
        String title,
        @Schema(description = "URL of the book, required for registration", example = "https://example.com/book/booktitle")
        String url,
        @Schema(description = "Book Tag List. Set words that describe the book's genre and content.", example = "[\"fight\", \"love\"]")
        List<String> tags,
        @Schema(description = "List of book authors. Set up the name of the original author, artist, etc.", example = "[\"akira toriyama\"]")
        List<String> authors,
        @Schema(description = "List of book episodes. Set the episode number, episode title, and episode URL.", accessMode = Schema.AccessMode.READ_ONLY)
        List<Episode> episodes
) {
    public Book {
        if (Objects.isNull(title) || title.isBlank()) throw new IllegalArgumentException("");
        if (Objects.isNull(url) || url.isBlank()) throw new IllegalArgumentException("");
    }
}
