package com.github.okanikani223.vicar.books.others.controllers.dtos;

import io.swagger.v3.oas.annotations.media.Schema;

public record BookRegistrationInfo(
        @Schema(description = "ID automatically generated by the system")
        String id
) {}
